### ISSUE TITLE
Tapping "C" to insert Color frame on Sprite Node doesn't work rather it moves timeline highlighter to lower node.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1111] opened 2014-11-07 15:49 UTC
1. Launch Application.
2. Add CCSprite Node.
3. Select CCSprite Node.
4. Tap C.
   
   -- Result: Color animation is not added rather highlighter of node moves downwards.

This happened 3/3 times.

Found on SpriteBuilder-1.3.4-rc.1

Mac OS X: 10.10.
XCode: 6.0.

**Comment by cocojoe** [comment] 2014-11-07 16:28
This is a dupe of #1003 although this is a faster way to test it using 'c'

**Closed as completed by cocojoe** 2014-11-07 16:28 UTC
