### ISSUE TITLE
Saving with a nil Label BM-Font crashes Sprite Builder

### ISSUE THREAD

**Issue by tylerjhutchison** [spritebuilder/SpriteBuilder#395] opened 2014-04-23 00:04 UTC
Steps to Replicate:
1)Create a New file.
2)Document name:foo.ccb, Type: Layer, Size: 568x384
3)Drag a Label BM-Font onto the Layer (Do not edit any of the default settings)
4) Save
This will cause SpriteBuilder to quit unexpectedly.
If you reopen sprite builder and attempt to open foo.ccb, SpriteBuilder will quit unexpectedly.

I'm guessing this might be crashing because of the nil font name.

**Comment by vlidholt** [comment] 2014-04-23 00:10
Which version of SpriteBuilder are you using?

**Comment by tylerjhutchison** [comment] 2014-04-23 00:13
Whoops! sorry I forgot.
 v1.0.4

**Comment by slembcke** [comment] 2014-04-23 00:21
I dug into this a little. It looks like the problem is that it's saving "missing-font.fnt" into the CCB file. When reloading, it causes the absolute path lookup in [TexturePropertySetter setFontForNode:] to fail.

**Comment by vlidholt** [comment] 2014-04-23 00:55
This should have been fixed in 1.0.6, which should be available on the App Store now!

**Comment by vlidholt** [comment] 2014-04-23 00:56
Update: Seems to be working for me. :)

**Comment by NickyWeber** [comment] 2014-04-23 08:21
It was a cocos2d "bug", the setFnt method will now throw an exception any time the font is not working correctly and that exception is caught by SB. Maybe a git submodule update will do in case you're working with the source code.

**Comment by slembcke** [comment] 2014-04-23 16:00
Ah. I was using the master branch which appears to be very outdated. I thought it was supposed to be the latest stable version like with the Cocos2D repository. Ignore me...

**Comment by NickyWeber** [comment] 2014-05-19 06:33
Is this bug solved?

**Comment by Shahidwerplay** [comment] 2015-04-13 14:15
This issue is fixed 
Mac Os 10.10.0.
SB Version 1.4.9.
XCode 6.2

**Closed as completed** 2015-04-13 22:34 UTC
Labels: t: bug, s: question
