### ISSUE TITLE
(Enhancement) Open associated XCode project from SpriteBuilder file menu

### ISSUE THREAD

**Issue by kevinmkarol** [spritebuilder/SpriteBuilder#635] opened 2014-06-20 02:32 UTC
It would be great if it was possible to open the associated XCode file from within SpriteBuilder rather than having to locate it in finder and open it manually.

**Comment by NickyWeber** [comment] 2014-06-20 06:03
Possible duplicate of https://github.com/spritebuilder/SpriteBuilder/issues/605

**Closed as completed** 2014-06-23 22:51 UTC
Labels: s: duplicate, t: improvement
