### ISSUE TITLE
SpriteBuilder freezes after connecting an external monitor via DisplayPort

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#796] opened 2014-08-21 13:48 UTC
Whenever I disconnect one of my external monitors and reconnect it, SpriteBuilder freezes with the spinning candy icon. There is no recovery, right-clicking the app icon shows the "Force Quit" option after a short time.

This happens in both debug & release builds, and is not affected by what screen the SB window is currently shown when disconnecting/connecting. 

Note that the freeze occurs only after connecting the external monitor, disconnecting it is fine. It also happens with only one of the two monitors (Samsung SyncMaster 2433, serial number HS4P806271). The other monitor I can disconnect and connect without a freeze.

Here's the call stack when I hit pause in Xcode:

```
Thread 1, Queue : com.apple.main-thread
#0  0x00007fff8d5a6746 in __psynch_mutexwait ()
#1  0x00007fff97ca0779 in _pthread_mutex_lock ()
#2  0x00007fff9a9e27d3 in CVDisplayLink::stop() ()
#3  0x00007fff9a9faa4d in CVCGDisplayLink::displayReconfiguration(unsigned int, unsigned int) ()
#4  0x00007fff9a9fa9f3 in _cvDisplayLinkDisplayReconfigurationCallback(unsigned int, unsigned int, void*) ()
#5  0x00007fff96f354c4 in CGSReconfigNotifierCalloutListInvokeAll ()
#6  0x00007fff96fad404 in displayConfigFinalizedProc ()
#7  0x00007fff96c40664 in CGSPostLocalNotification ()
#8  0x00007fff96c83e12 in (anonymous namespace)::notify_datagram_handler(unsigned int, CGSDatagramType, void*, unsigned long, void*) ()
#9  0x00007fff96c3e601 in CGSDatagramReadStream::dispatch_next_main_queue_datagram() ()
#10 0x00007fff96c3d7f6 in CGSDatagramReadStream::dispatch_next_datagram() ()
#11 0x00007fff96c3d7bc in CGSDatagramReadStream::dispatch_datagrams() ()
#12 0x00007fff96c9e77c in ___ZN21CGSDatagramReadStream24dispatch_datagrams_asyncEP16dispatch_queue_sPS__block_invoke ()
#13 0x00007fff932a51bb in _dispatch_call_block_and_release ()
#14 0x00007fff932a228d in _dispatch_client_callout ()
#15 0x00007fff932a9ef0 in _dispatch_main_queue_callback_4CF ()
#16 0x00007fff98a364f9 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#17 0x00007fff989f1714 in __CFRunLoopRun ()
#18 0x00007fff989f0e75 in CFRunLoopRunSpecific ()
#19 0x00007fff9ab59a0d in RunCurrentEventLoopInMode ()
#20 0x00007fff9ab597b7 in ReceiveNextEventCommon ()
#21 0x00007fff9ab595bc in _BlockUntilNextEventMatchingListInModeWithFilter ()
#22 0x00007fff9413a24e in _DPSNextEvent ()
#23 0x00007fff9413989b in -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ()
#24 0x00007fff9412d99c in -[NSApplication run] ()
#25 0x00007fff94118783 in NSApplicationMain ()
#26 0x00000001000241f2 in main at /SpriteBuilder/SpriteBuilder/ccBuilder/main.m:9
```

Relevant system info, external monitors are connected via DisplayPort using DVI adapters:

```

Hardware Overview:

  Model Name:   iMac
  Model Identifier: iMac13,2
  Processor Name:   Intel Core i7
  Processor Speed:  3,4 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 8 MB
  Memory:   32 GB
  Boot ROM Version: IM131.010A.B05
  SMC Version (system): 2.11f14
  Serial Number (system):   xxxxxxxxx
  Hardware UUID:    xxxxxxxxxx


NVIDIA GeForce GTX 680MX:

  Chipset Model:    NVIDIA GeForce GTX 680MX
  Type: GPU
  Bus:  PCIe
  PCIe Lane Width:  x16
  VRAM (Total): 2048 MB
  Vendor:   NVIDIA (0x10de)
  Device ID:    0x11a3
  Revision ID:  0x00a2
  ROM Revision: 3707
  Displays:
iMac:
  Display Type: LCD
  Resolution:   2560 x 1440
  Pixel Depth:  32-Bit Color (ARGB8888)
  Main Display: Yes
  Mirror:   Off
  Online:   Yes
  Built-In: Yes
SyncMaster:
  Resolution:   1920 x 1200 @ 60 Hz
  Pixel Depth:  32-Bit Color (ARGB8888)
  Display Serial Number:    HS4P806271  
  Mirror:   Off
  Online:   Yes
  Rotation: Supported
SyncMaster:
  Resolution:   1920 x 1200 @ 60 Hz
  Pixel Depth:  32-Bit Color (ARGB8888)
  Display Serial Number:    H9XS302200  
  Mirror:   Off
  Online:   Yes
  Rotation: Supported

```

**Comment by NickyWeber** [comment] 2014-11-18 09:18
I am not able to reproduce this.

**Comment by LearnCocos2D** [comment] 2014-11-18 15:42
It's probably one of those fringe errors specific to a given hardware/driver. I can only reproduce it with one of the two monitors I have. Not something I do on a daily basis either. ;)

**Comment by NickyWeber** [comment] 2014-11-18 16:11
Shall we close this then?

**Comment by LearnCocos2D** [comment] 2014-11-18 16:12
Yes. I think it's enough to have it on record as a "known issue".

**Closed as completed** 2014-11-18 16:12 UTC
Labels: t: bug
