### ISSUE TITLE
Automatic Cocos2D update in Sprite Builder hangs

### ISSUE THREAD

**Issue by alexchime** [spritebuilder/SpriteBuilder#645] opened 2014-06-24 07:25 UTC
I made a copy of my existing project so I could test things with the new versions but when I tried to do the automatic cocos2D update, it just hangs there forever. If I try to cancel it, it also just hangs there and does nothing. I have to forcequit.

**Comment by NickyWeber** [comment] 2014-06-24 07:36
Heya, anything on the console?

**Comment by alexchime** [comment] 2014-06-24 08:58
Sorry I had to rephrase the topic title as well. This is in Sprite Builder. 

I have a project that used SB 1.0 files and Cocos2D 3.0. I made a copy of the project and then opened it up with Sprite Builder. Then it prompted the message to update the Cocos2D files to 3.1. After that, the update just hung and didn't go anywhere. Even after trying to cancel, it just hung there.

**Comment by jonnyijapan** [comment] 2014-06-24 09:40
I had the same problem. I downloaded and ran SB from github, and while trying to debug and figure out the cause, the upgrade suddenly worked without doing any changes. I remember it got stuck while trying to call another thread to update the upgrade alert text or something...

**Comment by NickyWeber** [comment] 2014-06-24 19:31
Alright, can you reproduce this with a recent revision? That would be very helpful to fix this bug.

**Comment by cocojoe** [comment] 2014-08-20 15:19
So I had the same problem, projects on one machine just refused to update and would have to kill SB.  However I've retested now with all the recent patches on the develop branch and it nicely updated a 1.1 project with no problems.

**Comment by christinakelly** [comment] 2014-09-04 19:45
This should be fixed with 1.2.0 - closing this issue.

**Closed as completed by christinakelly** 2014-09-04 19:45 UTC
Labels: t: bug
