### ISSUE TITLE
User is unable to drag more nodes when user drag and drop Sprite 9 Slice to the screen.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#961] opened 2014-10-14 05:47 UTC
1. Launch application.
2. Drag and Drop Sprite 9 Slice onto the screen.
3. Try to Drag Color Node on the screen.

Result: User is unable to drag more nodes on to the screen when user drag and drop Sprite 9 Slice to the screen.

Video Link: https://phabricator.apportable.com/T730

Build: SpriteBuilder 1.3 Beta 07

Mac OSX: 10.9.4

**Comment by NickyWeber** [comment] 2014-10-14 07:04
Duplicate of https://github.com/spritebuilder/SpriteBuilder/issues/897.

**Closed as completed by NickyWeber** 2014-10-14 07:04 UTC
Labels: s: duplicate

**Comment by sana20** [comment] 2014-10-14 07:36
+Hammad

Sana Shahzad
Quality Assurance Analyst _|_ we.R.play
_www.werplay.com http://www.werplay.com/_
