### ISSUE TITLE
National support for numbers

### ISSUE THREAD

**Issue by voldzi** [spritebuilder/SpriteBuilder#1013] opened 2014-10-19 06:53 UTC
In my language (Czech) we use as number separator sign "," (comma) in US there is "." (dot). When editing CCButton/CCNode etc. details there is mixture of US and national number separators. I would prefere have either only national or only US... (Example: CCNode.Position = 14.2 (US dot); CCNode.Scale = 1,1 (national comma); CCNode.Rotation = 0.0 (US dot); CCNode.Skew = 0,00 (national comma);...)

**Comment by NickyWeber** [comment] 2014-10-21 08:16
Yeah, I already created a fix but it has not been decided how to treat localization.

**Comment by NickyWeber** [comment] 2014-11-18 09:10
Duplicate of https://github.com/spritebuilder/SpriteBuilder/issues/862

**Closed as completed by NickyWeber** 2014-11-18 09:10 UTC
Labels: t: bug, s: duplicate
