### ISSUE TITLE
"ARC Semantic Issues" error is displayed when user tries to create glass effect through XCode.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1010] opened 2014-10-17 10:43 UTC
1. Clone CCEffect Demo project: 
   https://github.com/MakeGamesWithUs/CCEffectsDemo
2. Launch project on SBP.
3. Publish and Run on Xcode.
   
   --Result: "ARC Semantic Issues" ("No known class method for selector 'effectWithRefraction:refraction...") error is displayed when user tries to create glass effect through XCode.

![error](https://cloud.githubusercontent.com/assets/7566802/4677622/6942dfe4-55ea-11e4-8225-4f8bb73207e3.png)

Build: SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode: 5.0

**Comment by Ben-G** [comment] 2014-10-17 13:45
Hey Kanoot,

thanks for letting us know. The issue is fixed with the latest commit! If you find more issues with the tutorials it would be great to open the issue on the repository of the tutorial itself, that way I will see them right away.

**Closed as completed** 2014-11-18 09:02 UTC
