### ISSUE TITLE
Duplicate a CCB

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#898] opened 2014-10-06 10:18 UTC
Can we add an option to easily duplicate a CCB please.
I know you can `Save As` however the problem now is you can't navigate into the package folder when using the finder dialog presented in `Save As`.  Would be nicer to just have a `Duplicate As` which drops straight into the same folder as the original.

**Comment by Neophen** [comment] 2014-10-08 17:44
Double that

**Comment by LearnCocos2D** [comment] 2014-10-16 14:49
duplicate of issue #450

**Comment by LearnCocos2D** [comment] 2014-10-16 14:50
Duplicate should simply create a duplicate with an automatic name (ie "myscene (1).ccb") because the user can then simply rename it in file view.

**Comment by cocojoe** [comment] 2014-10-16 14:52
Agreed

**Comment by cocojoe** [comment] 2014-10-30 14:20
OK have built a foundation for this, find it difficult to place item as really dislike it being right next to delete so added it after the separator.

As it stands it will only be enabled when a CCB file is selected.

![duplicate context](https://cloud.githubusercontent.com/assets/928115/4844831/d021f4f2-603f-11e4-9113-e276e33dc62b.png)

It will create copies and give them a unique copy name.

![duplicate result](https://cloud.githubusercontent.com/assets/928115/4844843/dfd649e8-603f-11e4-9e9e-75a43f061dd7.png)

Will do pull in a bit.

**Comment by NickyWeber** [comment] 2014-10-30 14:29
That's cool!
Would be cool if contextual menus would show only what's available for a certain kind if options get too many. Some things don't make sense for certain selections.

**Comment by LearnCocos2D** [comment] 2014-10-30 17:07
Thumbs up!
Contextual meaning if you try this on an image the duplicate item should be grayed out? Probably makes little to no sense to duplicate anything _but_ CCB files. Correct me if I'm wrong.

**Comment by cocojoe** [comment] 2014-10-30 17:54
Yes, I've left it fairly open for adding more types however CCB only for
now.

On Thursday, 30 October 2014, Steffen Itterheim notifications@github.com
wrote:

> Thumbs up!
> Contextual meaning if you try this on an image the duplicate item should
> be grayed out?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spritebuilder/SpriteBuilder/issues/898#issuecomment-61129429
> .

## 

Martin

**Comment by ypmits** [comment] 2014-10-30 19:37
You guys are awesome. Excellent! I was looking for this exact feature today!

**Closed as completed** 2014-12-08 13:53 UTC
Labels: c: interface, t: feature

**Comment by andykorth** [comment] 2014-12-10 17:40
I used the Duplicate context item today! Although... I'd love to have Command-D do the duplication as well. That's the shortcut in Unity, so I'm pretty used to that. Let me know if I should make a new issue for this request.

**Comment by LearnCocos2D** [comment] 2014-12-10 20:03
+1
Ctrl+D is also used for duplicating by ... darn, can't remember. ;)
