### ISSUE TITLE
Input text inside text box is not pixelated when user adds CCEffect on Text Field.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1128] opened 2014-11-13 10:25 UTC
1. Launch SB.
2. Add Text field on to the mainScreen.ccb.
3. Add CCEffect and add Text Field as a child and add any effect let say Pixelate/Blur.
4. Publish project and run in XCode.
   
   -- Result: Input text inside text box is not pixelated when user adds CCEffect on Text Field.

![screen shot 2014-11-13 at 3 18 29 pm](https://cloud.githubusercontent.com/assets/7566802/5026710/a9c366ba-6b48-11e4-9933-b6ab7d199bce.png)

Build: SpriteBuilder-1.3.5-rc.2

MAC OS: 10.9.5
XCode: 6.0

**Comment by nsluke** [comment] 2014-11-19 22:27
I recreated your results, and found that there is no way to add a visual effect to a CCTextField. This may be an intentional decision, because it would become too difficult to read whatever text is in the field. /

You may want to try using the effect on a CCLabel, which has the ability to have a visual effect added to it.

If you want to get really hacky and come up with an interesting solution, you could:
1. Place a CCLabel over the CCTextField
2. Set the text of the label equal to whatever text is inside the text field
3. Set the color of the text inside the text field equal to its own background
Now you have text that has the CCEffect added to it!

**Comment by thayerandrews** [comment] 2014-12-30 21:23
I'm closing this as expected behavior. 

Though the background of CCTextField is drawn with Cocos2D's renderer, the input text is not (it is drawn with an overlayed UITextView or NSTextView). Because of this, it is not possible for CCEffects to alter the appearance of the text.

**Closed as completed by thayerandrews** 2014-12-30 21:23 UTC
Labels: t: bug
