### ISSUE TITLE
"SpriteBuilder was not detected on your system. Please install it and try again." pop up is displayed when user tries to install android plugin with SpriteBuilder version 1.4.0-beta.02

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1184] opened 2014-11-27 11:55 UTC
1. Download SpriteBuilder 1.4.0-beta.02.
2. Install SpriteBuilder.
3. Open the SpriteBuilder for once and close it.
4. Now download the android plugin and try to install it.
   
   -- Result: "SpriteBuilder was not detected on your system. Please install it and try again." pop up is displayed when user tries to install android plugin with SpriteBuilder version 1.4.0-beta.02

Build: SpriteBuilder version 1.4.0-beta.02
Mac OS X: 10.9.5
XCode: 6.0

![screen shot 2014-11-26 at 9 24 15 am](https://cloud.githubusercontent.com/assets/8393830/5216499/151aeb28-7656-11e4-99f9-230ad402226c.png)

![screen shot 2014-11-26 at 9 24 56 am](https://cloud.githubusercontent.com/assets/8393830/5216506/29141960-7656-11e4-9d52-72e6c82c05b8.png)

**Comment by NickyWeber** [comment] 2014-11-27 12:20
There's a spritebuilder 1.4.0?

**Comment by sana20** [comment] 2014-11-27 12:21
@NickyWeber yes we got the build in today's Adhoc.

**Comment by KristenY** [comment] 2014-11-28 01:42
@NickyWeber This is an internal-only daily build of the latest on develop branch.  We tagged it as 1.4.0-beta.02 since we need to use a tag for our buildbot system.  Let me know if a different naming convention would be more clear for internal builds though!

@sana20 I'm not able to reproduce this.  Did you install SpriteBuilder by opening the .dmg and dragging it to the Applications directory?  Any additional detail you could provide would be great.  Thanks!

**Comment by sana20** [comment] 2014-11-28 02:11
@KristenY yes i installed the SpriteBuilder by opening the .dmg and dragging it to the application. The SpriteBuilder installed successfully but the name of SpriteBuilder was SpriteBuilder 1.3 Beta, we even tried by renaming the file but the android plugin gave the same error both the times that it found no SpriteBuilder in the system.

**Comment by NickyWeber** [comment] 2014-11-28 11:45
Might be related to the xcconfig being used. I don't have access to the buildbot but there's another configuration file with that name: `SpriteBuilder 1.3 Beta.xcconfig`.

**Comment by sana20** [comment] 2014-11-28 14:21
Video link for the issue : https://drive.google.com/file/d/0B23s5OMd3iivc3FmcDZzX1dET3c/view?usp=sharing

**Comment by rkachowski** [comment] 2014-12-12 00:57
This is due to 1.4.0-beta.02 not storing the spritebuilder user id anywhere except in NSUserDefaults, this has been fixed for a while and will be resolved in the next beta release.

**Comment by sana20** [comment] 2014-12-17 07:29
This issue is re-occurring.

Build: SpriteBuilder-1.4.0-beta.1

Mac OS X: 10.10
XCode: 6.1

**Comment by collinjackson** [comment] 2014-12-17 07:58
I think the installer is probably only looking for the user id in the sandboxed location, we need to also look for it in the non sandboxed location.

**Comment by sana20** [comment] 2014-12-17 08:08
Tried it on three macs:

(working on this one)
Mac OS X: 10.10.1
XCode: 6.0

(not working on the below combinations)
Mac OS X: 10.10
XCode: 6.0

Mac OS X: 10.10.1
XCode: 6.1

**Comment by rkachowski** [comment] 2014-12-17 09:02
Can you please retest with a version > 1.4.0-beta.02 - as mentioned above this issue is due to how spritebuilder saves the userid to the file system.

**Comment by collinjackson** [comment] 2014-12-18 04:46
This should be fixed in the beta build that went out tonight.

http://forum.spritebuilder.com/t/spritebuilder-1-4-beta-release/2573

**Closed as completed by collinjackson** 2014-12-18 04:46 UTC
