### ISSUE TITLE
Deleting a package containing ccbResurces, deletes all the other packages in the resource browser.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#935] opened 2014-10-13 11:20 UTC
1. Launch SBP.
2. Create a new project.
3. Add 2 gradient nodes and add particle effect (snow effect) to MainScene.ccb.
4. Create a new package.
   --Observe: Current project got packed in the package.
5. Delete the package containing ccbResurces.
   
   --Result: Deleting a package containing ccbResurces, deletes all the other packages in the resource browser. Particle effect on the stage gets distorted. 

For video view this ticket:
https://phabricator.apportable.com/T735

**Build:** SpriteBuilder 1.3 Beta 07

**Important Note:** Creating a new package after that all the packages are deleted, retrieves the previously deleted package except the the one containing ccbResources package. 

MAC OS: 10.9.0
XCode version: 5.0

**Comment by NickyWeber** [comment] 2014-10-16 09:09
As of bb5ceb32fb8a3295eed1c9c323a9876443621a23 I cannot reproduce this bug. I saw it happen. It must have been a regression fixed by the recent commits.

We need a new beta version to test this.

**Comment by sana20** [comment] 2014-10-30 11:17
This issue is re-occurring.
Build: SpriteBuilder-1.3.0-rc.1
Mac OS X: 10.9.0
XCode: 5.0

**Comment by NickyWeber** [comment] 2014-10-31 09:13
This is actually working correctly: If there is only one package only the contents are shown in the resource manager. If that one is empty, there won't be anyhting if it become the only one.

Please add a file to the new package and then delete the first one. The resource manager will only show that one file added to the new package.

I agree that a ccb should be closed if it was just deleted.

**Comment by Kanoot** [comment] 2014-10-31 14:36
This issue is fixed, it works as explained in NickyWeber's comment above.

Build: SpriteBuilder-1.3.0-rc.1.zip

MAC OS: 10.9.0
XCode: 5.0

**Closed as completed** 2014-11-05 15:01 UTC
Labels: t: bug, p: normal
