### ISSUE TITLE
Crash when importing incorrect bmfont files

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#225] opened 2014-01-28 00:44 UTC
When trying to use an incorrect bmfont file/folder SpriteBuilder crashes. SpriteBuilder should do some sort of validation when importing the bmfont folders.

**Comment by jtwigg** [comment] 2014-01-29 19:27
Can you clarify? Steps to repro? Missing folders like resources-tablet seem to fail gracefully even when viewing tablet resolutions.

1) Whats an 'incorrect bmfont file'.
2) What is an incorrect bmfont folder?

**Comment by vlidholt** [comment] 2014-03-13 02:44
Incorrect font: https://drive.google.com/file/d/0BzFSRgoEwrfXMlFUX0h1X19OOFU/edit?usp=sharing
Correct font: https://drive.google.com/file/d/0BzFSRgoEwrfXclVaUGdNaGNOM2M/edit?usp=sharing

Not sure what's up with the broken font, but also check the forums & documentation, lots of people having trouble with bitmap fonts. We need to fail gracefully with some descriptive pop-up message if a font is in an invalid format.

**Comment by NickyWeber** [comment] 2014-03-13 15:49
I don't have access to the crash logs, but I have feeling that the problem is even more general.
You can easily create a crash by inserting a bmfont node and then hit cmd+s saving the file -> crash.
Will investigate more.

**Comment by NickyWeber** [comment] 2014-03-21 07:51
Needs a fix in Cocos2D: CCLabelBMFont -setFntFile to gracefully handle errors by a Cocos2D consumer.

**Comment by NickyWeber** [comment] 2014-04-14 12:29
Fixed in cocos2d v3.0 branch.

**Closed as completed by NickyWeber** 2014-04-14 12:29 UTC
Labels: t: improvement, p: low
