### ISSUE TITLE
Losen the "no spaces allowed" restriction when creating a SpriteBuilder project

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#1219] opened 2014-12-11 12:24 UTC
Apparently one can only use [a-z][A-Z][0-9] in a project name. It's not just that spaces are disallowed, dashes (hyphens) and underscores aren't allowed either yet they are perfectly safe to use and rather common in filenames, especially where spaces aren't allowed or tedious to work with.

I believe there's a built-in function that trims a filename to a legal filesystem name, and then one could remove or replace space characters (and other potentially problematic ones like $ or ! perhaps?) from that, too.

The behavior should also be changed from a notification to the user, then aborting, to just fixing the project name and (optionally) informing the user about that but creating the project anyway but with the problematic characters consistently replaced (for instance by dashes or underscores) and the string properly trimmed (ie "Hello!!!" shouldn't become "Hello___" but "Hello").

**Comment by cocojoe** [comment] 2014-12-11 12:28
Name creation was tided up a bit, sounds like it may be a little too tight now. @rkachowski You minding having a look please.

**Comment by NickyWeber** [comment] 2014-12-11 14:36
Try to make an XCode project and give it a funny name. You can add all kinds of stuff. I was working on this but have not finished it yet.

Duplicate of https://github.com/spritebuilder/SpriteBuilder/issues/370

**Comment by rkachowski** [comment] 2014-12-11 17:33
Only the new file / new resource filename restriction (not project) were modified, and that only enforces a minimum of alphanumeric characters. But ideally both resources and projects be using the same system to validate filenames - so I'll look into unifying this.

**Comment by LearnCocos2D** [comment] 2014-12-18 10:50
Caution: I just found out from the [Android Plugin docs](http://android.spritebuilder.com/#known-issues) that spaces (but also other non-alphanumeric characters) can be problematic for the Android builds:

> Non-alphanumeric characters in the name of a .xcodeproj file will throw Package APK Tool Error. In particular, avoid spaces in the path to your project. Note: SpriteBuilder does not allow non-alpha-numeric project names to begin with.

**Comment by NickyWeber** [comment] 2014-12-18 12:40
Has this been tested? Even if SB prevents spaces in the project name itself, the path may contain them easily.

**Comment by rkachowski** [comment] 2015-01-07 11:54
The restriction was loosened in #1272, and given the discovery on restriction on spaces in path names I'm going to close this ticket. 

Feel free to reopen / create a new issue if the current functionality isn't enough.

**Closed as completed by rkachowski** 2015-01-07 11:54 UTC
Labels: s: duplicate, t: improvement
